name: e2e tests
on: [push]
jobs:
  test:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
        nE2E: 2
        marge: true
        browser: chrome
        before-run: |
          echo "CYPRESS_ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV
          npm run stop-only
        publish-summary: true
    secrets: inherit
        


