name: e2e tests
on: [push]
jobs:
  test:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    secrets: inherit
    with:
        nE2E: 2
        marge: true
        browser: chrome
        before-run: npm run stop-only
        publish-summary: true
        env: |
          CYPRESS_ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          npm run stop-only
        


